services:
    db:
      image: postgres:16
      restart: always
      environment:
            POSTGRES_USER: skillmate
            POSTGRES_PASSWORD: supersecret
            POSTGRES_DB: skillmate_db
      volumes:
            - postgres_data:/var/lib/postgresql/data
      ports:
            - "5432:5432" 
    backend:

      build: 
        context: .
        dockerfile: Dockerfile
      container_name: skillmate-backend
      #command: sh -c "PYTHONPATH=./backend/src uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
      volumes:
        - ./backend/src:/app/backend/src
      env_file:
        - backend/.env.docker
      ports:
        - "8000:8000"
      depends_on:
        - db
      #So unless you're intentionally overriding it (e.g., in CI/CD), it’s better to keep a single source of truth:
      # environment: 
      #   DATABASE_URL: postgresql+psycopg2://skillmate:supersecret@db:5432/skillmate_db
      restart: unless-stopped
    frontend:
      build:
        context: .
        dockerfile: client/Dockerfile
      container_name: skillmate-frontend
      ports:
        - "3000:80"
      depends_on:
        - backend
volumes:
  postgres_data:  