"""Create user_roles table.

Revision ID: e9b8e7a972f6
Revises:
Create Date: 2025-07-29 22:13:38.237184

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# import sqlmodel


# revision identifiers, used by Alembic.
revision: str = "e9b8e7a972f6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade table schema for database."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.add_column("user", sa.Column("user_role_id", sa.Integer(), nullable=True))
    op.create_foreign_key(None, "user", "user_roles", ["user_role_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade table schema for rollbacks."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="foreignkey")
    op.drop_column("user", "user_role_id")
    op.drop_table("user_roles")
    # ### end Alembic commands ###
