"""Add icon_path column to Skill model.

Revision ID: f9a8f677a0bd
Revises: d62332c6d555
Create Date: 2025-08-18 19:44:00.732314.

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "f9a8f677a0bd"
down_revision: Union[str, Sequence[str], None] = "d62332c6d555"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "skills",
        sa.Column("icon_path", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("skills", "icon_path")
    # ### end Alembic commands ###
