name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: 🐍 Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        # requirements.txt is at the root, so no `working-directory` needed here.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run pytest with coverage
        # No working-directory needed here either, as we want to run
        # the command from the root to make 'backend/src' relative to it.
        run: |
          pytest --cov=backend/src --cov-report=xml --cov-report=term-missing
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
         files: ./coverage.xml
         flags: backend
         name: backend-tests

  frontend:
    name: ⚛️ Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        working-directory: client
        run: npm install

      - name: Run Vitest
        working-directory: client
        run: npm test