name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  backend:
    name: 🐍 Backend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        # requirements.txt is at the root, so no `working-directory` needed here.
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Set up backend test environment
        run: |
         echo "database_url=sqlite:///:memory:" >> backend/.env
         echo "secret_key=test_secret" >> backend/.env
    #   - name: Copy test env file
    #     run: cp backend/.env.test backend/.env
      
      - name: Run pytest with coverage
        # env:
        #  DATABASE_URL: ${{ secrets.DATABASE_URL }} # Use GitHub Secrets
        #  SECRET_KEY: ${{ secrets.SECRET_KEY }}     # Use GitHub Secrets
        # No working-directory needed here either, as we want to run
        # the command from the root to make 'backend/src' relative to it.
        run: |
          PYTHONPATH=backend/src pytest --cov=backend/src --cov-report=xml --cov-report=term-missing
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
         files: ./coverage.xml
         flags: backend
         name: backend-tests

  frontend:
    name: ⚛️ Frontend Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Clean install dependencies
        working-directory: client
        run: |
            rm -rf node_modules
            npm ci

      - name: Run Vitest
        working-directory: client
        run: npm run test:coverage
        
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
                flags: frontend
                files: ./client/coverage/lcov.info